spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: spring-cloud-test-microservicecloud-config-dev #开发环境
---
spring:
  profiles: test
  application:
    name: spring-cloud-test-microservicecloud-config-test #测试环境